languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://peterramaldes.com"
canonifyurls = true
title = "Peter A. Ramaldes"
author = "peterramaldes"
theme = "pixyll"
 
[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 10
    ordered = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  twitter_username = "peterramaldes"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
