languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://peterramaldes.com"
canonifyurls = true
title = "Peter A. Ramaldes"
author = "peterramaldes"
theme = "pixyll"
 
[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 10
    ordered = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  twitter_username = "peterramaldes"

